# Generated by Django 4.0.6 on 2025-05-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_customer_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('sorting_order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('fiscal_year', models.CharField(max_length=20)),
                ('agent_name', models.CharField(max_length=255, null=True)),
                ('transaction_date_time', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_in_words', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, default='Cash', max_length=255, null=True)),
                ('print_count', models.PositiveIntegerField(default=1)),
                ('receipt_count_number', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer')),
            ],
            options={
                'unique_together': {('receipt_number', 'fiscal_year')},
            },
        ),
    ]
