# Generated by Django 4.0.6 on 2025-05-19 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='customer',
        ),
    ]
