# Generated by Django 4.0.6 on 2025-05-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_tbljournalentry_purchase'),
        ('receipt', '0002_remove_receipt_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='received_from_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts_sent_from_customer', to='accounting.accountledger'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='received_to_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts_received_to_ledger', to='accounting.accountledger'),
        ),
    ]
