# Generated by Django 4.0.6 on 2025-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_dashain_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
