# Generated by Django 4.0.6 on 2025-04-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_requisitionbranchstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_canteen_item',
            field=models.BooleanField(default=False),
        ),
    ]
