# Generated by Django 4.0.6 on 2025-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_is_canteen_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lunch_type',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('egg', 'Egg')], help_text='Applicable only for canteen items', max_length=10, null=True, verbose_name='Lunch Type'),
        ),
    ]
