# Generated by Django 4.0.6 on 2025-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_lunch_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_class',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum class for this product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_class',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum class for this product', null=True),
        ),
    ]
