# Generated by Django 4.0.6 on 2025-05-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_bill_is_end_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
