# Generated by Django 4.0.6 on 2025-05-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_tblpurchaseentry_grn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpurchase',
            name='quantity',
        ),
    ]
