# Generated by Django 4.0.6 on 2025-05-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_remove_productpurchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpurchase',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
