# Generated by Django 4.0.6 on 2025-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_productpurchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
