# Generated by Django 4.0.6 on 2025-05-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_purchase_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_id',
        ),
    ]
