# Generated by Django 4.0.6 on 2025-05-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_remove_purchase_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpurchaseentry',
            name='purchase_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
