# Generated by Django 4.0.6 on 2025-04-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='bill_created',
            field=models.BooleanField(default=False),
        ),
    ]
