# Generated by Django 4.0.6 on 2025-04-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_studentattendance_bill_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
