# Generated by Django 4.0.6 on 2025-04-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_studentattendance_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
