# Generated by Django 4.0.6 on 2025-04-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_lunch_type'),
        ('canteen', '0004_studentattendance_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
