# Generated by Django 4.0.6 on 2025-04-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_lunch_type'),
        ('canteen', '0007_tblmissedattendance_preinformedleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblmissedattendance',
            name='considered_next_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblmissedattendance',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
