# Generated by Django 4.0.6 on 2025-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0011_monthlyadjustments_delete_schoolholidaycredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyadjustments',
            name='valid_for_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyadjustments',
            name='valid_for_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
