# Generated by Django 4.0.6 on 2025-04-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='roll_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='student_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
