# Generated by Django 4.0.6 on 2025-04-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer_roll_no_customer_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='roll_no',
        ),
    ]
