# Generated by Django 4.0.6 on 2025-04-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customer_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='meal_preference',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('egg', 'Egg')], max_length=10, null=True, verbose_name='Custtomer Meal Type'),
        ),
    ]
