# Generated by Django 4.0.6 on 2025-04-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_customer_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='student_class',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
